### PR TITLE
feat: Lambda Role Name

### PR DESCRIPTION
**Pull request by e4r7hbug**
Provide a way to generate Lambda IAM Role names.

See also: https://github.com/gogoair/foremast/pull/112

### CODE REVIEW

**Comment by sijis** [comment]
Test cases needed.

**Comment by e4r7hbug** [comment]
I got your tests. I got your tests **right here**!

**Comment by sijis** [comment]
Everything looks good. The last thing needed is the Readme update.

**Comment by e4r7hbug** [comment]
README! Done.

**Pull request merged**
